node {
   def mvnHome
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/nigelrobbins/pipeline.git'
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.           
   }
   stage('Build') {
      // Run the maven build
      if (isUnix()) {
         echo 'build'
      }
   }
   stage('Results') {
      // Run the maven build
      if (isUnix()) {
         echo 'results'
      }
   }
}
